# Generated by Django 5.0.2 on 2024-04-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_is_active_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
