# Generated by Django 3.2.12 on 2024-03-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categoris/images'),
        ),
    ]
