# Generated by Django 3.2.12 on 2024-03-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='D_project.Tags'),
        ),
    ]
