# Generated by Django 5.0.2 on 2024-03-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0002_donation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
