# Generated by Django 3.2.12 on 2024-03-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0003_auto_20240306_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
