# Generated by Django 5.0.2 on 2024-03-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0003_alter_rate_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remaining_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
