# Generated by Django 3.2.12 on 2024-03-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0004_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images'),
        ),
    ]
