# Generated by Django 5.0.2 on 2024-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0004_project_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='remaining_amount',
            field=models.FloatField(default=100, null=True),
        ),
    ]
