# Generated by Django 3.2.12 on 2024-03-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='projects/images'),
        ),
    ]
