# Generated by Django 5.0.3 on 2024-03-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0009_comment'),
        ('D_project', '0009_donation_rate'),
    ]

    operations = [
    ]
