# Generated by Django 5.0.3 on 2024-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D_project", "0010_merge_0009_comment_0009_donation_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(related_name="projects", to="D_project.tag"),
        ),
    ]
