# Generated by Django 5.0.3 on 2024-03-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0012_donation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='target',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
