# Generated by Django 5.0.3 on 2024-03-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0012_reply'),
        ('D_project', '0013_alter_donation_donation_alter_project_target'),
    ]

    operations = [
    ]
