# Generated by Django 5.0.3 on 2024-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0014_merge_20240308_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='D_project.tag'),
        ),
    ]
