# Generated by Django 5.0.3 on 2024-03-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0016_alter_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
