# Generated by Django 5.0.3 on 2024-03-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0018_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
