# Generated by Django 5.0.3 on 2024-03-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0019_comment_is_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reported',
        ),
    ]
