# Generated by Django 5.0.3 on 2024-03-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D_project', '0017_project_is_featured'),
        ('D_project', '0020_remove_comment_is_reported'),
    ]

    operations = [
    ]
